"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getShopifyId = exports["default"] = void 0;

var _regenerator = _interopRequireDefault(require("@babel/runtime/regenerator"));

var _inherits2 = _interopRequireDefault(require("@babel/runtime/helpers/inherits"));

var _possibleConstructorReturn2 = _interopRequireDefault(require("@babel/runtime/helpers/possibleConstructorReturn"));

var _getPrototypeOf2 = _interopRequireDefault(require("@babel/runtime/helpers/getPrototypeOf"));

var _wrapNativeSuper2 = _interopRequireDefault(require("@babel/runtime/helpers/wrapNativeSuper"));

var _typeof2 = _interopRequireDefault(require("@babel/runtime/helpers/typeof"));

var _defineProperty2 = _interopRequireDefault(require("@babel/runtime/helpers/defineProperty"));

var _asyncToGenerator2 = _interopRequireDefault(require("@babel/runtime/helpers/asyncToGenerator"));

var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));

var _createClass2 = _interopRequireDefault(require("@babel/runtime/helpers/createClass"));

var _axios = _interopRequireDefault(require("axios"));

function _createSuper(Derived) { var hasNativeReflectConstruct = _isNativeReflectConstruct(); return function _createSuperInternal() { var Super = (0, _getPrototypeOf2["default"])(Derived), result; if (hasNativeReflectConstruct) { var NewTarget = (0, _getPrototypeOf2["default"])(this).constructor; result = Reflect.construct(Super, arguments, NewTarget); } else { result = Super.apply(this, arguments); } return (0, _possibleConstructorReturn2["default"])(this, result); }; }

function _isNativeReflectConstruct() { if (typeof Reflect === "undefined" || !Reflect.construct) return false; if (Reflect.construct.sham) return false; if (typeof Proxy === "function") return true; try { Date.prototype.toString.call(Reflect.construct(Date, [], function () {})); return true; } catch (e) { return false; } }

function ownKeys(object, enumerableOnly) { var keys = Object.keys(object); if (Object.getOwnPropertySymbols) { var symbols = Object.getOwnPropertySymbols(object); if (enumerableOnly) symbols = symbols.filter(function (sym) { return Object.getOwnPropertyDescriptor(object, sym).enumerable; }); keys.push.apply(keys, symbols); } return keys; }

function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; if (i % 2) { ownKeys(Object(source), true).forEach(function (key) { (0, _defineProperty2["default"])(target, key, source[key]); }); } else if (Object.getOwnPropertyDescriptors) { Object.defineProperties(target, Object.getOwnPropertyDescriptors(source)); } else { ownKeys(Object(source)).forEach(function (key) { Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key)); }); } } return target; }

// Generated by CoffeeScript 2.5.1
// Deps
var ShopifyGtmInstrumentor,
    StorefrontError,
    fetchVariantQuery,
    indexOf = [].indexOf;

// Main class, which accepts configuration in it's constructor and exposes
// helper methods
var _default = ShopifyGtmInstrumentor = /*#__PURE__*/function () {
  // Save settings and hydrate vars
  function ShopifyGtmInstrumentor() {
    var _ref = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {},
        _ref$debug = _ref.debug,
        debug = _ref$debug === void 0 ? false : _ref$debug,
        _ref$storeUrl = _ref.storeUrl,
        storeUrl = _ref$storeUrl === void 0 ? process.env.SHOPIFY_URL : _ref$storeUrl,
        _ref$storefrontToken = _ref.storefrontToken,
        storefrontToken = _ref$storefrontToken === void 0 ? process.env.SHOPIFY_STOREFONT_TOKEN : _ref$storefrontToken,
        _ref$currencyCode = _ref.currencyCode,
        currencyCode = _ref$currencyCode === void 0 ? 'USD' : _ref$currencyCode;

    (0, _classCallCheck2["default"])(this, ShopifyGtmInstrumentor);
    this.debug = debug;
    this.storeUrl = storeUrl;
    this.storefrontToken = storefrontToken;
    this.currencyCode = currencyCode;
    this.occurances = [];
  } // API #######################################################################
  // Typically used for view of PDP page


  (0, _createClass2["default"])(ShopifyGtmInstrumentor, [{
    key: "viewProductDetails",
    value: function () {
      var _viewProductDetails = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee(variantPayload) {
        var flatVariant, variant;
        return _regenerator["default"].wrap(function _callee$(_context) {
          while (1) {
            switch (_context.prev = _context.next) {
              case 0:
                _context.next = 2;
                return this.getVariantFromPayload(variantPayload);

              case 2:
                variant = _context.sent;
                return _context.abrupt("return", this.pushEvent('View Product Details', _objectSpread(_objectSpread({}, flatVariant = this.makeFlatVariant(variant)), {}, {
                  ecommerce: {
                    detail: {
                      products: [this.makeUaProductFieldObject(flatVariant)]
                    }
                  }
                })));

              case 4:
              case "end":
                return _context.stop();
            }
          }
        }, _callee, this);
      }));

      function viewProductDetails(_x) {
        return _viewProductDetails.apply(this, arguments);
      }

      return viewProductDetails;
    }() // Used whenver there is a positive change in the quantity of a product in
    // the cart.

  }, {
    key: "addProductToCart",
    value: function addProductToCart(variantPayload, quantity) {
      return this.updateQuantity(variantPayload, quantity, 'Add to Cart', 'add');
    } // Used whenever there is a negative change in the quantity of a product in
    // the cart.

  }, {
    key: "removeProductFromCart",
    value: function removeProductFromCart(variantPayload, quantity) {
      return this.updateQuantity(variantPayload, quantity, 'Remove from Cart', 'remove');
    } // Used both fire the `Update Quantity` event but also as a helper for the
    // add and remove methods.

  }, {
    key: "updateQuantity",
    value: function () {
      var _updateQuantity = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee2(variantPayload, quantity) {
        var gtmEvent,
            ecommerceAction,
            flatVariant,
            variant,
            _args2 = arguments;
        return _regenerator["default"].wrap(function _callee2$(_context2) {
          while (1) {
            switch (_context2.prev = _context2.next) {
              case 0:
                gtmEvent = _args2.length > 2 && _args2[2] !== undefined ? _args2[2] : 'Update Quantity';
                ecommerceAction = _args2.length > 3 ? _args2[3] : undefined;
                _context2.next = 4;
                return this.getVariantFromPayload(variantPayload);

              case 4:
                variant = _context2.sent;
                return _context2.abrupt("return", this.pushEvent(gtmEvent, _objectSpread(_objectSpread({}, flatVariant = this.makeFlatVariant(variant)), !ecommerceAction ? {} : {
                  ecommerce: (0, _defineProperty2["default"])({
                    currencyCode: this.currencyCode
                  }, ecommerceAction, {
                    products: [_objectSpread(_objectSpread({}, this.makeUaProductFieldObject(flatVariant)), {}, {
                      quantity: quantity
                    })]
                  })
                })));

              case 6:
              case "end":
                return _context2.stop();
            }
          }
        }, _callee2, this);
      }));

      function updateQuantity(_x2, _x3) {
        return _updateQuantity.apply(this, arguments);
      }

      return updateQuantity;
    }() // Notify of final checkout, using array of variant data from liquid

  }, {
    key: "purchase",
    value: function purchase(lineItems) {
      return this.pushEvent('Purchase', {
        lineItems: lineItems
      });
    } // DATA HELPERS ##############################################################
    // Take a variantPayload, which may be an id or an object, and return the
    // Shopify variant object, ideally with nsted product data.

  }, {
    key: "getVariantFromPayload",
    value: function getVariantFromPayload(variantPayload) {
      if ((0, _typeof2["default"])(variantPayload) === 'object') {
        return variantPayload;
      } else {
        return this.fetchVariant(variantPayload);
      }
    } // Lookup a product variant by id. Id may be a simple number or a
    // gid://shopify string

  }, {
    key: "fetchVariant",
    value: function () {
      var _fetchVariant = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee3(variantId) {
        var result;
        return _regenerator["default"].wrap(function _callee3$(_context3) {
          while (1) {
            switch (_context3.prev = _context3.next) {
              case 0:
                variantId = getShopifyId(variantId);
                _context3.next = 3;
                return this.queryStorefrontApi({
                  variables: {
                    id: btoa('gid://shopify/ProductVariant/' + variantId)
                  },
                  query: fetchVariantQuery
                });

              case 3:
                result = _context3.sent;
                return _context3.abrupt("return", result.node);

              case 5:
              case "end":
                return _context3.stop();
            }
          }
        }, _callee3, this);
      }));

      function fetchVariant(_x4) {
        return _fetchVariant.apply(this, arguments);
      }

      return fetchVariant;
    }() // Make flat object from a variant with nested product data

  }, {
    key: "makeFlatVariant",
    value: function makeFlatVariant(variant) {
      var ref, ref1, ref2, ref3;
      return {
        // Variant level data
        sku: variant.sku,
        variantId: getShopifyId(variant.id),
        variantTitle: variant.title,
        price: variant.price,
        // Product level info
        productTitle: (ref = variant.product) != null ? ref.title : void 0,
        productType: ((ref1 = variant.product) != null ? ref1.productType : void 0) || ((ref2 = variant.product) != null ? ref2.type : void 0),
        productVendor: (ref3 = variant.product) != null ? ref3.vendor : void 0
      };
    } // Convert a Shopify variant object to a UA productFieldObject. I'm
    // comibing the product and variant name because that's what Shopify does
    // with it's own events.
    // https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#product-data

  }, {
    key: "makeUaProductFieldObject",
    value: function makeUaProductFieldObject(flatVariant) {
      return {
        id: flatVariant.sku,
        name: flatVariant.productTitle + ' - ' + flatVariant.variantTitle,
        brand: flatVariant.productVendor,
        category: flatVariant.productType,
        variant: flatVariant.variantTitle,
        price: flatVariant.price
      };
    } // STOREFRONT API ############################################################
    // Query Storefront API

  }, {
    key: "queryStorefrontApi",
    value: function () {
      var _queryStorefrontApi = (0, _asyncToGenerator2["default"])( /*#__PURE__*/_regenerator["default"].mark(function _callee4(payload) {
        var response;
        return _regenerator["default"].wrap(function _callee4$(_context4) {
          while (1) {
            switch (_context4.prev = _context4.next) {
              case 0:
                _context4.next = 2;
                return (0, _axios["default"])({
                  url: "".concat(this.storeUrl, "/api/2021-04/graphql"),
                  method: 'post',
                  headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                    'X-Shopify-Storefront-Access-Token': this.storefrontToken
                  },
                  data: payload
                });

              case 2:
                response = _context4.sent;

                if (!response.data.errors) {
                  _context4.next = 5;
                  break;
                }

                throw new StorefrontError(response.data.errors, payload);

              case 5:
                return _context4.abrupt("return", response.data.data);

              case 6:
              case "end":
                return _context4.stop();
            }
          }
        }, _callee4, this);
      }));

      function queryStorefrontApi(_x5) {
        return _queryStorefrontApi.apply(this, arguments);
      }

      return queryStorefrontApi;
    }() // DATALAYER WRITING #########################################################
    // Push GTM dataLayer event

  }, {
    key: "pushEvent",
    value: function pushEvent(name, payload) {
      if (this.debug) {
        console.debug("'".concat(name, "'"), payload);
      }

      if (!window.dataLayer) {
        window.dataLayer = [];
      }

      return window.dataLayer.push(_objectSpread({
        event: name,
        firstOccurance: this.isFirstOccurance(name)
      }, payload));
    } // Return whether this is the first time the event has fired. This can be
    // helpeful in conjunction to prevent double triggering from events that are
    // also fired in the intial page response from Shopify, like Page Views.

  }, {
    key: "isFirstOccurance",
    value: function isFirstOccurance(eventName) {
      if (indexOf.call(this.occurances, eventName) >= 0) {
        return false;
      }

      this.occurances.push(eventName);
      return true;
    }
  }]);
  return ShopifyGtmInstrumentor;
}();

exports["default"] = _default;

StorefrontError = function () {
  // NON-INSTANCE HELPERS ########################################################
  // Error object with custom handling
  var StorefrontError = /*#__PURE__*/function (_Error) {
    (0, _inherits2["default"])(StorefrontError, _Error);

    var _super = _createSuper(StorefrontError);

    function StorefrontError(errors, payload) {
      var _this;

      (0, _classCallCheck2["default"])(this, StorefrontError);
      _this = _super.call(this, errors.map(function (e) {
        return e.debugMessage || e.message;
      }).join(', '));
      _this.errors = errors.map(function (e) {
        return JSON.stringify(e);
      });
      _this.payload = payload;
      return _this;
    }

    return StorefrontError;
  }( /*#__PURE__*/(0, _wrapNativeSuper2["default"])(Error));

  ;
  StorefrontError.prototype.name = 'StorefrontError';
  return StorefrontError;
}.call(void 0); // Graphql query to fetch a variant by id


fetchVariantQuery = "query ($id: ID!) {\n\tnode(id: $id) {\n\t\t... on ProductVariant {\n\t\t\tid\n\t\t\tsku\n\t\t\ttitle\n\t\t\tprice\n\t\t\tproduct {\n\t\t\t\ttitle\n\t\t\t\tproductType\n\t\t\t\tvendor\n\t\t\t}\n\t\t}\n\t}\n}"; // Get the id from a Shoify gid:// style id.  This strips everything but the
// last part of the string.  So gid://shopify/ProductVariant/34641879105581
// becomes 34641879105581

var getShopifyId = function getShopifyId(id) {
  var ref;

  if (String(id).match(/^\d+$/)) {
    // Already simple id
    return id;
  }

  if (!id.match(/^gid:\/\//)) {
    // De-base64
    id = atob(id);
  }

  return (ref = id.match(/\/(\w+)$/)) != null ? ref[1] : void 0;
};

exports.getShopifyId = getShopifyId;